SNAKE-11 API Регистрации
multiplayersnake/snake pull request #19
Opened 2022-01-20 00:51 UTC by prince-lvov

2022-01-20 05:24 UTC, ndronov requested changes

2022-01-20 05:24 UTC, ndronov commented on src/api/AuthAPI.ts
> +  nickname: string;
давайте вместо `nickname` использовать `login`

2022-01-20 05:24 UTC, ndronov commented on src/services/AuthService.ts
> +      newUserData = Object.assign({ first_name: '', second_name: '', phone: '89215555555' }, newUserData);
напиши лучше вот так:
```js
      const newUserData = getSubmittedFormData<SignUpRequest>(e);
      const placeholderData = { first_name: '', second_name: '', phone: '89215555555' };
      const data = { ...newUserData, ...placeholderData };
      
      await authAPI.signUp(data);
```

2022-01-20 06:23 UTC, Totentu commented on src/api/AuthAPI.ts
> +  nickname: string;
Нет, нет, это же два разных поля и там дальше есть логин. login - это имя для авторизации, а nickname - это отображаемое игровое имя.

2022-01-20 06:26 UTC, Totentu commented
Несколько общих правок к странице регистрации:
- На странице регистрации в заголовке осталась картинка с английским заголовком. Нужно заменить на правильный заголовок.
- Предлагаю изменить порядок полей при регистрации на более привычный, что ли. Сначала логин и пароль, затем почта и ник.

2022-01-20 06:36 UTC, Totentu requested changes
Оставил комментарии.

2022-01-20 08:36 UTC, Totentu commented
При попытке зарегистрироваться под уже существующим логином система не выдает ничего. А хотелось бы хоть как-то увидеть ответ ошибки, чтобы понимать, что не так.

Я зарегистрировал нового пользователя. Однако его display_name не сформировался. И я только что понял, что функционал регистрации и не подразумевает формирование display_name, он формируется только уже при работе с пользователем. Предложение: в качестве ника (игрового имени, позывного) можно использовать first_name,  а не display_name т.к. его можно сформировать сразу при регистрации. Т.е. при регистрации, поле с игровым именем передавать в first_name, а я заменю во всех компонентах, в которых сейчас выводится display_name на first_name.

2022-01-20 09:38 UTC, ndronov commented on src/api/AuthAPI.ts
> +  nickname: string;
используем first_name для хранения nickname

2022-01-21 08:42 UTC, ndronov approved these changes

2022-01-21 09:12 UTC, Totentu requested changes
Все отлично, визуально осталось несколько пунктов:
1. Порядок полей при регистрации сделать стандартным: логин, пароль, почта, позывной.
2. В заголовке страницы регистрации заменить картинку на h1.
3. Вернуть шрифт заголовка на Seymour One (похожий на картинку прототипа).
4. Либо убрать Impact, либо научить его писать кириллицей.

2022-01-21 10:14 UTC, Totentu approved these changes

2022-01-21 10:14 UTC, merged