Snake-46 OAuth with Yandex
multiplayersnake/snake pull request #32
Opened 2022-02-16 02:25 UTC by prince-lvov

2022-02-16 06:49 UTC, Totentu requested changes
Саша, тебе нужно включить линтер, который учитывает правила написания кода, указанные в конфигурации нашего проекта. Очевидно он у тебя не работает, иначе он бы тебе указал на все эти неточности.

2022-02-16 06:49 UTC, Totentu commented on src/api/AuthAPI/AuthAPI.ts
> +  code : string;
Пробел перед двоеточием нужно убрать.

2022-02-16 06:49 UTC, Totentu commented on src/api/AuthAPI/AuthAPI.ts
> +  service_id : string;
Пробел перед двоеточием нужно убрать.

2022-02-16 06:49 UTC, Totentu commented on src/api/AuthAPI/AuthAPI.ts
> +  redirect_uri : string;
Пробел перед двоеточием нужно убрать.

2022-02-16 06:49 UTC, Totentu commented on src/api/AuthAPI/AuthAPI.ts
> +}
Пропущена точка с запятой

2022-02-16 06:49 UTC, Totentu commented on src/api/AuthAPI/AuthAPI.ts
> +  }
Пропущена точка с запятой

2022-02-16 06:49 UTC, Totentu commented on src/hooks/useAuth/useAuth.tsx
> +  )
Пропущена точка с запятой

2022-02-16 06:49 UTC, Totentu commented on src/services/AuthService.ts
> +
В этом блоке много аналогичных синтаксических неточностей (проблемы перед двоеточием, пропущены точки с запятыми). Очень нужно включить линтер.

2022-02-16 07:02 UTC, Totentu commented
И один практический комментарий-вопрос. Это ведь должно работать? Но вот у меня при попытке авторизоваться получилось так:

![image](https://user-images.githubusercontent.com/84324342/154213073-1725d114-6a0a-45a6-890a-ae3e351cc400.png)

2022-02-16 09:29 UTC, ndronov commented on src/api/AuthAPI/AuthAPI.ts
> +  code : string;
типы с большой буквы

2022-02-16 09:31 UTC, ndronov commented on src/api/AuthAPI/AuthAPI.ts
> +    return this.http.get<ServiceId>('/yandex/service-id?redirect_uri=http://localhost:8080/login');
как-то странно в API завязываться на `http://localhost:8080/login`

2022-02-16 09:35 UTC, ndronov commented on src/services/AuthService.ts
> +      await oauthAPI.signInWithYandex(data)
надо обсудить и понять, что тут происходит

2022-02-22 13:21 UTC, ndronov approved these changes

2022-02-22 13:30 UTC, Totentu approved these changes

2022-02-22 13:56 UTC, merged