SNAKE-47 Внедрение работы с базой данных
multiplayersnake/snake pull request #38
Opened 2022-02-23 16:20 UTC by Totentu

…общениями форума.

2022-02-24 13:46 UTC, ndronov commented on docker-compose.yaml
> +      - awesome
думаю, надо назвать более осмысленно, например `snake`

2022-02-24 13:46 UTC, ndronov commented on package.json
> +    "@ckeditor/ckeditor5-build-classic": "^32.0.0",
предлагаю все зависимости поддерживать с точным указанием версии без знака `^`

2022-02-24 13:47 UTC, ndronov commented on src/api/HTTP.ts
> +// export const BASE_URL = 'https://ya-praktikum.tech/api/v2';
это можно удалить

2022-02-24 13:48 UTC, ndronov commented on src/api/HTTP.ts
> +import { IMessage } from '../database/models/message';
предлагаю не испольовать `I` d интерфейсах, пусть будет `MessageType`
и может лучше назвать это комментарием - `CommentType` ?

2022-02-24 13:49 UTC, ndronov commented on src/components/common/Button/NavButton.tsx
> +    */
можно просто закомментровать или удалить `console.log`

2022-02-24 13:50 UTC, ndronov commented on src/components/forum/Message/Message.tsx
> +import { CKEditor } from '@ckeditor/ckeditor5-react';
на что ругается ts ?

2022-02-24 13:51 UTC, ndronov commented on src/api/HTTP.ts
> +  data?: FormData | ObjectLike | IMessage;
если IMessage описать не как интерфейс, а как тип, то его не надо будет сюда добавлять

2022-02-24 13:53 UTC, ndronov commented on src/api/MessagesAPI.ts
> +      data: data
можно проcто `data`

https://alligator.io/js/object-property-shorthand-es6/

2022-02-24 13:53 UTC, ndronov commented on src/api/MessagesAPI.ts
> +  public readMessage(topic_id: number): Promise<IMessage[]> {
camelCase

2022-02-24 13:53 UTC, ndronov commented on src/api/MessagesAPI.ts
> +      data: data
просто `data`

2022-02-24 13:54 UTC, ndronov commented on src/database/api/message.ts
> +      topic_id: topic_id
просто `topic_id`

2022-02-24 13:56 UTC, ndronov commented on src/server.ts
> +app.get([`/api/messages/read/:topic_id`], async (req, res) => {
можно обходиться без /read/ и /update/ в URL, за уточнение действия отвечает метод

2022-02-24 13:58 UTC, ndronov commented on src/server.ts
> +  req.on('data', async function (chunk) {
я бы вынес эти функцит в папку server

2022-02-24 13:58 UTC, ndronov commented on src/server.ts
> +app.post([`/api/messages/create`], (req, res) => {
я бы вынес обработчики API в папку `server`

2022-02-24 14:00 UTC, Totentu commented on .env
> +POSTGRES_PASSWORD=1234
Эм... так это же и есть этот файл

2022-02-24 14:01 UTC, ndronov requested changes

2022-02-24 14:01 UTC, ndronov commented on .env
> +POSTGRES_PASSWORD=1234
а пароль не надо вынести в .env ?

2022-02-24 14:29 UTC, ndronov commented on .env
> +POSTGRES_PASSWORD=1234
ок

2022-02-25 10:00 UTC, ndronov approved these changes

2022-02-25 10:11 UTC, merged