SNAKE-48 Форум: бэкенд для топиков
multiplayersnake/snake pull request #41
Opened 2022-03-05 10:11 UTC by ndronov

2022-03-08 09:47 UTC, spt30 requested changes

2022-03-08 09:47 UTC, spt30 commented on src/components/forum/Message/Message.tsx
> +          key={`${editMode}`}
`key={editMode}` было бы достаточно

2022-03-08 09:47 UTC, spt30 commented on src/components/forum/Topic/Topic.tsx
> +    (e?) => {
тут синтаксис какой-то странный

2022-03-08 09:47 UTC, spt30 commented on src/components/forum/Topic/Topic.tsx
> +            Удалить
Сейчас, наверное, поздно переделывать, но на будущее: весь пользовательский контент лучше хранить нормализованно — например, все текста хорошо бы положить в отдельный файлик (можно прям объектом сплошняком); полезно это в том случае, когда вас, например, неожиданно попросят сделать локализацию для другого языка: не придется судорожно бегать по всем файликам и проверять, все ли переводы вставили

Вообще в целом если можно за условно бесплатно оставить точку расширения, для которой существует понятный юзкейс — лучше ее оставить, чем не оставить (с) Далай-лама

2022-03-08 09:47 UTC, spt30 commented on src/pages/ForumPage/ForumPage.tsx
> +// import { TopicWithTimeStamps } from '../../database/models';
мусор остался

2022-03-08 09:47 UTC, spt30 commented on src/pages/ForumPage/ForumPage.tsx
> +  }, []);
Напрямую обращаться к АПИ из компонента — плохо: это сразу блокирует возможности для повторного использования данных, для более тонкой настройки запросов, для качественных сайд-эффектов при успешном и неуспешном запросе, а также для обработки исключений после неудачного запроса; а если не блокирует, то по крайней мере, потребует больших усилий

Правильно будет использовать библиотеку для реализации асинхронных запросов в редаксе —сейчас модно писать на связке redux-toolkit + rtk-query, но можно также посмотреть в сторону react-query или более классических базовых вариантов: redux-thunk (он, кстати, входит в redux-toolkit), redux-saga (она, кстати, не обновлялась 3 года, но многие её используют в том числе на новых проектах (как и express,  например)); они все суть одинаковые: в компоненте нужно будет диспатчить какой-то action, на этот action будет завязана saga/thunk/promise/effect/epic (нужное подчеркнуть), который выполнит необходимые операции в нужной последовательности, а затем задиспатчит другой action, reducer для которого положит его данные из action.payload уже в store... Теперь в компоненте останется заиспользовать useSelector и забрать данные из стора

Это пример стандартной реализации асинхронной операции над данными во flux-архитектуре; если писать так, как написано сейчас — смысл редакса и вообще однонаправленного потока данных в приложении теряется

2022-03-09 03:15 UTC, ndronov commented on src/components/forum/Message/Message.tsx
> +          key={`${editMode}`}
![image](https://user-images.githubusercontent.com/26296037/157365825-82b15d9f-7b18-4b85-a2c0-15aaed088de7.png)
ts думает иначе )

2022-03-09 03:17 UTC, ndronov commented on src/components/forum/Topic/Topic.tsx
> +    (e?) => {
функция вызывается в двух местах, в одном случае из кода и без параметров, а во втором случае как обработчик клика, и нужно вызвать `e?.stopPropagation();`

2022-03-09 03:19 UTC, ndronov commented on src/components/forum/Topic/Topic.tsx
> +            Удалить
да, согласен, но так как в постановке задач вроде бы ни слова об этом не было, мы даже и не задумались об этом

2022-03-09 03:19 UTC, ndronov commented on src/pages/ForumPage/ForumPage.tsx
> +// import { TopicWithTimeStamps } from '../../database/models';
убрал

2022-03-09 08:44 UTC, spt30 commented on src/components/forum/Message/Message.tsx
> +          key={`${editMode}`}
а, хм
а ему точно нужен key? тут же мы не итерируемся, кажется, он не нужен

2022-03-09 10:17 UTC, ndronov commented on src/pages/ForumPage/ForumPage.tsx
> +  }, []);
понял, оставлю комментарий, что надо будет переработать

2022-03-09 10:18 UTC, ndronov commented on src/components/forum/Message/Message.tsx
> +          key={`${editMode}`}
без этого почему-то CKEditor не реагирует на обновление пропса data

2022-03-09 10:20 UTC, merged