SNAKE-23 Страница входа
multiplayersnake/snake pull request #7
Opened 2021-12-23 03:12 UTC by ndronov

https://trello.com/c/xYxFif6s

2021-12-24 08:57 UTC, Totentu reviewed
Перед тем, как сделать эту ветку основой для всей дальнейшей разработки, внес некоторые комментарии (в основном мелкие правки).

2021-12-24 08:57 UTC, Totentu commented on src/components/LogoutLink/LogoutLink.tsx
> +    <a href="/" onClick={handleClick}>
Кнопка "Выйти" должна не только делать logout пользователя, но и переводить роутер на страницу авторизации.

2021-12-24 08:57 UTC, Totentu commented on src/pages/LoginPage/LoginPage.tsx
> +          <Button type="submit">Войти</Button>
Кнопка "Войти" при успешном входе должна переводить роутер на главную страницу. А при неуспешном выдавать причину провала.

2021-12-24 08:57 UTC, Totentu commented on src/components/App/App.tsx
> +        <NavMenu hidden={false} user={user} onAction={handleAction} />
Мне кажется, что меню навигации уже можно скрыть полностью. Для этого есть главная страница. В крайнем случае, мы же знаем path всех страниц, можно вписать вручную.

2021-12-24 08:57 UTC, Totentu commented on src/components/Heading/Heading.css
> +  color: var(--violet);
Не знаю, будет ли видна картинка, в общем, есть разница в написании заголовков. Такое ощущение, что они отличаются параметров font-weight. Т.е. заголовки как будто написаны **жирным** , а должны быть обычные.
![img_000001_edu](https://user-images.githubusercontent.com/84324342/147336717-8cf72f46-b455-44d8-afc6-98a411c03a8c.jpg)

2021-12-24 08:57 UTC, Totentu commented on src/api/HTTP.ts
> +export default class HTTP {
Саша вчера на созвоне очень "сокрушался" по поводу использования этого механизма запросов и говорил различные слова, вроде fetch и aoix. Я просто оставлю здесь пометку, я пока не настолько компетентен, чтобы участвовать в этой дискуссии.

2021-12-24 09:16 UTC, ndronov commented on src/components/LogoutLink/LogoutLink.tsx
> +    <a href="/" onClick={handleClick}>
да, ты прав, пока не реализовал это,
наврено заведу отдельную задачу по логике редиректов.

2021-12-24 09:18 UTC, ndronov commented on src/pages/LoginPage/LoginPage.tsx
> +          <Button type="submit">Войти</Button>
Да, показ ошибок хорошая идея, 
но там много невидимых с первого взгляда сложностей, попробую реализовать, если останется время.

2021-12-24 09:18 UTC, ndronov commented on src/components/App/App.tsx
> +        <NavMenu hidden={false} user={user} onAction={handleAction} />
Я пока теряюсь без этого меню ))
предлаю оставить ещё на некоторое время.

2021-12-24 09:21 UTC, ndronov commented on src/components/Heading/Heading.css
> +  color: var(--violet);
![image](https://user-images.githubusercontent.com/26296037/147339398-ce32171e-4cad-4e97-a16f-9f093c5dff64.png)

ты прав, браузер по умолчанию делает все заголовки жирными, поправлю это.

2021-12-24 09:23 UTC, ndronov commented on src/api/HTTP.ts
> +export default class HTTP {
Внутри исопльзуется fetch, HTTP это просто обёртка, но возможно она действительно лишняя,
надо подумать об этом...

2021-12-24 09:28 UTC, ndronov commented on src/api/HTTP.ts
> +  data?: FormData | unknown;
как описать тип вмето unknown, чтобы он мог принимать объекты с произвольным интерфейсом? 

```typescript
interface {
id: number;

}
```

2021-12-25 16:45 UTC, spt30 requested changes
cn в целом используется неправильно и классы получаются именованными не по БЭМу

давайте попробуем переписать (можно прямо отдельным ПРом) на правильное использование
я обычно пользуюсь таким разделением: 
- один файл — один Блок (в файле иногда может быть несколько компонентов, если представится случай, расскажу, почему это иногда удобно)
- в случае необходимости можно создать служебный блок (для верстки, например, иногда пригождается)
- по возможности в каждом компоненте реализовать возможность прокинуть mix в пропсах, который навесится на Блок (или на какой-то Элемент, если контрол сложный)
- отступаться от вышеизложенного можно, если это оправдано, это — не догма
- отступаться от общих принципов БЭМа нельзя, это — догма

2021-12-25 16:45 UTC, spt30 commented on src/api/HTTP.ts
> +  data?: FormData | unknown;
тут разобрались вроде

2021-12-25 16:45 UTC, spt30 commented on src/api/handleAPIError.ts
> +function handleAPIError(serializedError: Error) {
по-моему тут ошибка как раз несериализованная
но вообще с точки зрения ее обработки это не важно — лучше просто назвать error

2021-12-25 16:45 UTC, spt30 commented on src/api/handleAPIError.ts
> +    console.log('API error:', error);
Ваня Акулов как-то раз писал про то, почему плохо не выводить всю ошибку: https://t.me/iamakulov_channel/465

Давай тут будем делать просто console.error(serializedError)

2021-12-25 16:45 UTC, spt30 commented on src/api/handleAPIError.ts
> +    console.log('API error:', error);
тогда и catch будет не нужен

2021-12-25 16:45 UTC, spt30 commented on src/components/Button/NavButton.tsx
> +export default NavButton;
на будущее: лучше не использовать дефолтные экспорты, если можно их не использовать — они создают кучу проблем с автоподсказками и переименованием функций и так далее

2021-12-25 16:45 UTC, spt30 commented on src/components/Button/NavButton.tsx
> +export default NavButton;
имеет смысл только в том случае, если используется динамический импорт, но это нужно крайне редко

2021-12-25 16:45 UTC, spt30 commented on src/components/Button/NavButton.tsx
> +  };
такие обработчики хорошо бы оборачивать в useCallback

2021-12-25 16:45 UTC, spt30 commented on src/components/Form/Form.tsx
> +    <form {...rest} className={cn('form', className)}>
```
const onClick = useCallback((e: FormEvent) => {
    e.preventDefault();
    props?.onClick(e);
})

<form {...rest} className={cn('form', className)} onClick={onClick}>
```

2021-12-25 16:45 UTC, spt30 commented on src/components/Input/Input.css
> +  align-self: stretch;
этому элементу не нужен align-self, т.к. по умолчанию он не находится во flex-контейнере

2021-12-25 16:45 UTC, spt30 commented on src/components/LogoutLink/LogoutLink.tsx
> +    [onClick]
вот тут классно прям

2021-12-25 16:45 UTC, spt30 commented on src/components/LogoutLink/LogoutLink.tsx
> +      Выйти
Весь текстовый контент лучше сразу выносить в отдельный файл где-нибудь в корне src (можно просто объект сделать)
Просто для того, чтобы если вдруг вас попросят перевести ваше приложение на другой язык, не бегать как обезьяна по всему проекту и не подменять текста на функции

2021-12-25 16:45 UTC, spt30 commented on src/hooks/useAuth/useAuth.ts
> +  const [user, setUser] = useState<User | undefined>(undefined);
null наверное

2021-12-25 16:45 UTC, spt30 commented on src/hooks/useAuth/useAuth.ts
> +  const authorized = useMemo(() => !!user, [user]);
`!!` плохо читается глазом, лучше `Boolean()`

2021-12-25 16:45 UTC, spt30 commented on src/hooks/useAuth/useAuth.ts
> +  const authorized = useMemo(() => !!user, [user]);
булевские переменные лучше называть с is, has, have

2021-12-25 16:45 UTC, spt30 commented on src/hooks/useAuth/useAuth.ts
> +    await AuthService.signIn(e);
тут signIn, а выше logOut
давай как-то одинаково именовать

2021-12-25 16:45 UTC, spt30 commented on src/components/NavMenu/NavMenu.tsx
> +      <ul className={cn('nav-menu-items', hidden && 'nav-menu-items_hidden')}>
`cn('nav-menu-items', { hidden })`

2021-12-25 16:45 UTC, spt30 commented on src/services/AuthService.ts
> +      return undefined;
return;

2021-12-25 16:45 UTC, spt30 commented on src/services/getSubmittedFormData.ts
> +  return nonEmptyFields as unknown as T;
черная магия))

2021-12-26 03:09 UTC, ndronov commented on src/components/Input/Input.css
> +  align-self: stretch;
![image](https://user-images.githubusercontent.com/26296037/147397951-d4a1acfb-d247-4abf-802c-71b4c35dbbc3.png)
наша форма - flex-контейнер

2021-12-26 03:10 UTC, ndronov commented on src/components/LogoutLink/LogoutLink.tsx
> +      Выйти
ох, на это наврено надо завести отдельную задачу

2021-12-26 03:19 UTC, ndronov commented on src/hooks/useAuth/useAuth.ts
> +  const [user, setUser] = useState<User | undefined>(undefined);
c одной тсороны ты прав, но с другой, тогда вот такое не работает
![image](https://user-images.githubusercontent.com/26296037/147398068-7fa33c2f-e1ac-48e5-abd5-beae1421308a.png)
и придётся писать `User | null`

2021-12-26 03:26 UTC, ndronov commented on src/hooks/useAuth/useAuth.ts
> +  const authorized = useMemo(() => !!user, [user]);
в данном случае решил не усложнять, оно ведь и так понятно )

2021-12-26 03:28 UTC, ndronov commented on src/hooks/useAuth/useAuth.ts
> +    await AuthService.signIn(e);
![image](https://user-images.githubusercontent.com/26296037/147398158-9c579f06-7a1e-4426-be79-b817e2bcf9fb.png)
в данном случае я просто порвторяю опиcание API :)

2021-12-26 03:33 UTC, ndronov commented on src/services/getSubmittedFormData.ts
> +  return nonEmptyFields as unknown as T;
![image](https://user-images.githubusercontent.com/26296037/147398191-fdd850ea-ed7d-481e-a9e0-51f5c3a622eb.png)
не придумал как убрать эту ошибку

2021-12-26 15:58 UTC, ndronov commented
> cn в целом используется неправильно и классы получаются именованными не по БЭМу
> 
> давайте попробуем переписать (можно прямо отдельным ПРом) на правильное использование я обычно пользуюсь таким разделением:
> 
> * один файл — один Блок (в файле иногда может быть несколько компонентов, если представится случай, расскажу, почему это иногда удобно)
> * в случае необходимости можно создать служебный блок (для верстки, например, иногда пригождается)
> * по возможности в каждом компоненте реализовать возможность прокинуть mix в пропсах, который навесится на Блок (или на какой-то Элемент, если контрол сложный)
> * отступаться от вышеизложенного можно, если это оправдано, это — не догма
> * отступаться от общих принципов БЭМа нельзя, это — догма

@spt30 я не помню, чтобы где-то оговраивалось, что мы пишем код по БЭМу

2021-12-27 06:32 UTC, merged

2021-12-27 10:10 UTC, spt30 commented
> @spt30 я не помню, чтобы где-то оговаривалось, что мы пишем код по БЭМу

черт, а сейчас действительно такого требования нет... интересно

2021-12-27 10:13 UTC, spt30 commented on src/components/Input/Input.css
> +  align-self: stretch;
Да, но с точки зрения компонента никакого флекс-контейнера нет
Такие вещи нужно делать подмиксовывая className из родительского компонента
Компонент должен быть самостоятельным, если он лежит в отдельном файле — без лишних стилей

2021-12-27 10:14 UTC, spt30 commented on src/components/LogoutLink/LogoutLink.tsx
> +      Выйти
Давай тут переделаем и сделаем задачку, чтобы по проекту пройтись и перенести

2021-12-27 10:17 UTC, spt30 commented on src/hooks/useAuth/useAuth.ts
> +    await AuthService.signIn(e);
тут не поправлено