SNAKE-15 Страница регистрации
multiplayersnake/snake pull request #9
Opened 2022-01-02 01:58 UTC by prince-lvov

https://trello.com/c/2BsAxWA6/15-%D1%81%D1%82%D1%80%D0%B0%D0%BD%D0%B8%D1%86%D0%B0-%D1%80%D0%B5%D0%B3%D0%B8%D1%81%D1%82%D1%80%D0%B0%D1%86%D0%B8%D0%B8

2022-01-02 06:49 UTC, Totentu approved these changes
В целом все очень точно, а мои комментарии-вопросы не принципиальны, все это можно поправить потом.

2022-01-02 06:49 UTC, Totentu commented on src/pages/SignupPage/SignupPage.tsx
> +      <img className="logo" src={logo} alt={'logo'} />
Нужно принять решения. Я вот был уверен, что дизайнер предложила просто вариант оформления главного заголовка, и сделал (на главной странице или странице форума) css приближенный вариант, но чтобы название могло быть на нужном языке (например, русском, или любом другом). А ты предлагаешь картинку...

В целом не принципиально, просто нужно принять решение, какой вариант мы будем считать правильным, с точки зрения разработки.

2022-01-02 06:49 UTC, Totentu commented on src/fonts/noto.css
> +  src: url('http://www.yoursite.com/fonts/Avenir_Next.otf');
А я все не мог понять, что это вообще за шрифт. Если мы его подключаем в проект, то его нужно подключить как основной в базовом файле fonts.css. А что это за сайт такой? Почему не разместить его внутри нашего проекта, если мы его выбираем в качестве основного?

Предлагаю тоже обсудить, хочу в этом разобраться.

2022-01-03 06:19 UTC, ndronov commented on README.md
> +Усовершенстоваванные макеты экранов:
опечатка

2022-01-03 06:23 UTC, ndronov commented on src/fonts/noto.css
> +}
что такое "noto" ?

2022-01-03 06:25 UTC, ndronov commented on src/components/Input/Input.tsx
> +      <input {...rest} value={label} className={cn('input', className)} />
теперь value всегда будет равно лэйблу, явно ошибка. 
лэйбл это лэйбл, а значение это занчение.

2022-01-03 06:30 UTC, ndronov commented on README.md
> +https://www.figma.com/file/shSFDN4NMBizZwGSua7XHc/Snake?node-id=1%3A5887
по поводу новых макетов: как будет выглядеть лэйбл для заполненного инпута?
![image](https://user-images.githubusercontent.com/26296037/147904423-b0c00da2-a052-49c7-9b68-3c59f1c48ac3.png)

2022-01-03 12:08 UTC, prince-lvov commented on README.md
> +https://www.figma.com/file/shSFDN4NMBizZwGSua7XHc/Snake?node-id=1%3A5887
![image](https://user-images.githubusercontent.com/85033131/147928632-4b094b4d-04cd-4c96-8c65-e864e4f5025e.png)

2022-01-03 23:36 UTC, ndronov commented on README.md
> +https://www.figma.com/file/shSFDN4NMBizZwGSua7XHc/Snake?node-id=1%3A5887
значит в компоненте Input не нужно удалять
```jsx
<span className="input-label">{label}</span>
```

2022-01-03 23:37 UTC, ndronov requested changes

2022-01-03 23:37 UTC, ndronov commented on README.md
> +Усовершенстоваванные макеты экранов:
опечатка

2022-01-04 18:23 UTC, prince-lvov commented on src/fonts/noto.css
> +}
Убрал noto, осознав что шрифты подключаем исключительно в fonts.css

2022-01-04 19:33 UTC, prince-lvov commented on src/fonts/noto.css
> +  src: url('http://www.yoursite.com/fonts/Avenir_Next.otf');
Все подключение уже происходит в fonts.css. В assets/fonts же добавлены файлы, отвечающие за кроссбраузерность отображения конкретного начертания. 
![image](https://user-images.githubusercontent.com/85033131/148113631-0cdb2ec9-26fe-4287-8d69-909efaca9a7f.png)
С таким подходом мы не попадем в ситуацию, когда нет интернета и шрифтов тоже не станет, все выкачано и как в рили проекте.

2022-01-04 19:36 UTC, prince-lvov commented on src/pages/SignupPage/SignupPage.tsx
> +      <img className="logo" src={logo} alt={'logo'} />
![image](https://user-images.githubusercontent.com/85033131/148113893-0376d3d1-6ba2-4658-b108-f6f6c142acca.png)

С картинкой красивее:
![image](https://user-images.githubusercontent.com/85033131/148113956-7d76e5e3-63de-4348-9ef6-606e862b2324.png)

2022-01-04 22:39 UTC, prince-lvov commented on README.md
> +https://www.figma.com/file/shSFDN4NMBizZwGSua7XHc/Snake?node-id=1%3A5887
Все сделал. Сейчас все работает правильно, и в то же время согласно стилям инпутов.
![image](https://user-images.githubusercontent.com/85033131/148133591-df0b86db-bc86-4ff6-a0c7-15ea18d1dca7.png)
![image](https://user-images.githubusercontent.com/85033131/148133615-e18502b3-3aa9-4e0d-8642-7784a152defa.png)

2022-01-04 22:41 UTC, prince-lvov commented on src/fonts/noto.css
> +  src: url('http://www.yoursite.com/fonts/Avenir_Next.otf');
![image](https://user-images.githubusercontent.com/85033131/148133756-d1f62bfa-958e-4c1c-935d-ce322fe751ae.png)
Все начертания, которые используются в проекте подключил. У каждого начертания шрифта по 4 файла

2022-01-04 22:42 UTC, prince-lvov commented on src/fonts/noto.css
> +  src: url('http://www.yoursite.com/fonts/Avenir_Next.otf');
Одно начертание у Impact и два начертания у Open Sans.

2022-01-05 04:22 UTC, ndronov commented on README.md
> +https://www.figma.com/file/shSFDN4NMBizZwGSua7XHc/Snake?node-id=1%3A5887
зачем reqiured={true} ?
{...rest} вполне достаточно

2022-01-05 04:24 UTC, ndronov commented on src/components/Input/Input.css
> +  font-family: var(--open_sans-font);
предлагаю называть переменные через kebab-case
https://techrocks.ru/2018/08/09/most-common-programming-case-types/

2022-01-05 04:26 UTC, ndronov commented on src/pages/SignupPage/SignupPage.tsx
> +      <img className="logo" src={logo} alt={'logo'} />
давайте весь интерфейс на русском сделаем

2022-01-05 04:28 UTC, ndronov commented on src/styles/fonts.css
> -  --platform-font: -apple-system, system-ui, BlinkMacSystemFont, 'Segoe UI', Roboto, 'Helvetica Neue', Arial, sans-serif;
если удалаешь переменную, надо удалить её использование во всём проекте

2022-01-18 07:21 UTC, ndronov approved these changes

2022-01-19 22:58 UTC, merged

2022-01-19 23:05 UTC, prince-lvov commented
Pull request влит в ветку `main` способом **Squash and merge** согласно CONTRIBUTING.md